# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.1'

    - name: Install Deps
      run: go mod tidy

    - name: Load environment variables from .env
      run: |
        echo "API_KEY=${{ secrets.NEXUS_KEY }}" >> .env

    - name: Test V1
      run: go test -v ./v1/tests/...
